name: KeepAlive
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create keepalive change on a branch
        run: |
          BRANCH="keepalive"
          echo -n " " >> whitespace.txt

          git config user.name "White Space Bot"
          git config user.email "whitespace[bot]@users.noreply.github.com"

          git checkout -B "$BRANCH"
          git add whitespace.txt
          git commit -m "chore: keepalive [skip ci]" || exit 0
          git push -u origin "$BRANCH" --force
